[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = """
      default-src 'self';
      frame-ancestors 'self';
      style-src-elem 'self' 'unsafe-inline';
      """
    Cross-Origin-Resource-Policy = "same-origin"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[redirects]]
  from = "/talks/*"
  to = "https://mefody.github.io/talks/:splat"
  status = 301

[[plugins]]
  package = "./plugins/webmention-cache"

[[plugins]]
  package = "netlify-plugin-webmentions"
  [plugins.inputs]
    baseUrl = "https://mefody.dev"
    feedPath = "/feed/rss.xml"
    limit = 3

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [ ".cache" ]
